# drake plan
plan <- drake_plan(
  # load data
  d = loadData(),
  # cronbach's alpha
  alpha1 = psych::alpha(d[,c("egame.SH.T10", "egame.TG1.T10", "egame.TG2.T10",
                             "egame.PGG.T10", "egame.DG.T10")]),
  alpha2 = psych::alpha(d[,c("Env.ClimateChgCause.T09", "Env.ClimateChgConcern.T09",
                             "Env.ClimateChgReal.T09")]),
  # confirmatory factor analyses
  cfa1 = cfaModel1(d),
  cfa2 = cfaModel2(d),
  # structural equation models
  sem1.01 = semModel1(d),
  sem1.02 = semModel1(d, controls = " + Age.T09"),
  sem1.03 = semModel1(d, controls = " + Gender.T09"),
  sem1.04 = semModel1(d, controls = " + EthnicCats.T09_Asian + EthnicCats.T09_Maori + EthnicCats.T09_Pacific"),
  sem1.05 = semModel1(d, controls = " + Pol.ReportedPartySupport.T09_Greens + Pol.ReportedPartySupport.T09_Labour + Pol.ReportedPartySupport.T09_NZFirst"),
  sem1.06 = semModel1(d, controls = " + NZREG.T09"),
  sem1.07 = semModel1(d, controls = " + T9.EXTRAVERSION"),
  sem1.08 = semModel1(d, controls = " + T9.AGREEABLENESS"),
  sem1.09 = semModel1(d, controls = " + T9.CONSCIENTIOUSNESS"),
  sem1.10 = semModel1(d, controls = " + T9.NEUROTICISM"),
  sem1.11 = semModel1(d, controls = " + T9.OPENNESS"),
  sem1.12 = semModel1(d, controls = " + T9.HONESTY_HUMILITY"),
  sem1.13 = semModel1(d, controls = " + T9.NARCISSISM"),
  sem1.14 = semModel1(d, controls = " + Age.T09 + Gender.T09 + EthnicCats.T09_Asian + EthnicCats.T09_Maori + EthnicCats.T09_Pacific + Pol.ReportedPartySupport.T09_Greens + Pol.ReportedPartySupport.T09_Labour + Pol.ReportedPartySupport.T09_NZFirst + NZREG.T09 + T9.EXTRAVERSION + T9.AGREEABLENESS + T9.CONSCIENTIOUSNESS + T9.NEUROTICISM + T9.OPENNESS + T9.HONESTY_HUMILITY + T9.NARCISSISM"),
  sem2.01 = semModel2(d),
  sem2.02 = semModel2(d, controls = " + Age.T09"),
  sem2.03 = semModel2(d, controls = " + Gender.T09"),
  sem2.04 = semModel2(d, controls = " + EthnicCats.T09_Asian + EthnicCats.T09_Maori + EthnicCats.T09_Pacific"),
  sem2.05 = semModel2(d, controls = " + Pol.ReportedPartySupport.T09_Greens + Pol.ReportedPartySupport.T09_Labour + Pol.ReportedPartySupport.T09_NZFirst"),
  sem2.06 = semModel2(d, controls = " + NZREG.T09"),
  sem2.07 = semModel2(d, controls = " + T9.EXTRAVERSION"),
  sem2.08 = semModel2(d, controls = " + T9.AGREEABLENESS"),
  sem2.09 = semModel2(d, controls = " + T9.CONSCIENTIOUSNESS"),
  sem2.10 = semModel2(d, controls = " + T9.NEUROTICISM"),
  sem2.11 = semModel2(d, controls = " + T9.OPENNESS"),
  sem2.12 = semModel2(d, controls = " + T9.HONESTY_HUMILITY"),
  sem2.13 = semModel2(d, controls = " + T9.NARCISSISM"),
  sem2.14 = semModel2(d, controls = " + Age.T09 + Gender.T09 + EthnicCats.T09_Asian + EthnicCats.T09_Maori + EthnicCats.T09_Pacific + Pol.ReportedPartySupport.T09_Greens + Pol.ReportedPartySupport.T09_Labour + Pol.ReportedPartySupport.T09_NZFirst + NZREG.T09 + T9.EXTRAVERSION + T9.AGREEABLENESS + T9.CONSCIENTIOUSNESS + T9.NEUROTICISM + T9.OPENNESS + T9.HONESTY_HUMILITY + T9.NARCISSISM"),
  sem3.01 = semModel3(d, var = "Env.ClimateChgCause.T09"),
  sem3.02 = semModel3(d, var = "Env.ClimateChgConcern.T09"),
  sem3.03 = semModel3(d, var = "Env.ClimateChgReal.T09"),
  sem4.01 = semModel4(d),
  # mediation models
  med1.01 = medModel1(d),
  med1.02 = medModel1(d, controls = " + Age.T09"),
  med1.03 = medModel1(d, controls = " + Gender.T09"),
  med1.04 = medModel1(d, controls = " + EthnicCats.T09_Asian + EthnicCats.T09_Maori + EthnicCats.T09_Pacific"),
  med1.05 = medModel1(d, controls = " + Pol.ReportedPartySupport.T09_Greens + Pol.ReportedPartySupport.T09_Labour + Pol.ReportedPartySupport.T09_NZFirst"),
  med1.06 = medModel1(d, controls = " + NZREG.T09"),
  med1.07 = medModel1(d, controls = " + T9.EXTRAVERSION"),
  med1.08 = medModel1(d, controls = " + T9.AGREEABLENESS"),
  med1.09 = medModel1(d, controls = " + T9.CONSCIENTIOUSNESS"),
  med1.10 = medModel1(d, controls = " + T9.NEUROTICISM"),
  med1.11 = medModel1(d, controls = " + T9.OPENNESS"),
  med1.12 = medModel1(d, controls = " + T9.HONESTY_HUMILITY"),
  med1.13 = medModel1(d, controls = " + T9.NARCISSISM"),
  med1.14 = medModel1(d, controls = " + Age.T09 + Gender.T09 + EthnicCats.T09_Asian + EthnicCats.T09_Maori + EthnicCats.T09_Pacific + Pol.ReportedPartySupport.T09_Greens + Pol.ReportedPartySupport.T09_Labour + Pol.ReportedPartySupport.T09_NZFirst + NZREG.T09 + T9.EXTRAVERSION + T9.AGREEABLENESS + T9.CONSCIENTIOUSNESS + T9.NEUROTICISM + T9.OPENNESS + T9.HONESTY_HUMILITY + T9.NARCISSISM"),
  med2.01 = medModel2(d),
  med2.02 = medModel2(d, controls = " + Age.T09"),
  med2.03 = medModel2(d, controls = " + Gender.T09"),
  med2.04 = medModel2(d, controls = " + EthnicCats.T09_Asian + EthnicCats.T09_Maori + EthnicCats.T09_Pacific"),
  med2.05 = medModel2(d, controls = " + Pol.ReportedPartySupport.T09_Greens + Pol.ReportedPartySupport.T09_Labour + Pol.ReportedPartySupport.T09_NZFirst"),
  med2.06 = medModel2(d, controls = " + NZREG.T09"),
  med2.07 = medModel2(d, controls = " + T9.EXTRAVERSION"),
  med2.08 = medModel2(d, controls = " + T9.AGREEABLENESS"),
  med2.09 = medModel2(d, controls = " + T9.CONSCIENTIOUSNESS"),
  med2.10 = medModel2(d, controls = " + T9.NEUROTICISM"),
  med2.11 = medModel2(d, controls = " + T9.OPENNESS"),
  med2.12 = medModel2(d, controls = " + T9.HONESTY_HUMILITY"),
  med2.13 = medModel2(d, controls = " + T9.NARCISSISM"),
  med2.14 = medModel2(d, controls = " + Age.T09 + Gender.T09 + EthnicCats.T09_Asian + EthnicCats.T09_Maori + EthnicCats.T09_Pacific + Pol.ReportedPartySupport.T09_Greens + Pol.ReportedPartySupport.T09_Labour + Pol.ReportedPartySupport.T09_NZFirst + NZREG.T09 + T9.EXTRAVERSION + T9.AGREEABLENESS + T9.CONSCIENTIOUSNESS + T9.NEUROTICISM + T9.OPENNESS + T9.HONESTY_HUMILITY + T9.NARCISSISM"),
  # r2 data
  r2data = dataR2(d, sem1.01, sem1.14, sem2.01, sem2.14),
  # plots
  mainPlot = plotMain(d, cfa1, cfa2),
  coefPlot = plotCoef(sem1.01, sem1.02, sem1.03, sem1.04, sem1.05, sem1.06, sem1.07, 
                      sem1.08, sem1.09, sem1.10, sem1.11, sem1.12, sem1.13, sem1.14, 
                      sem2.01, sem2.02, sem2.03, sem2.04, sem2.05, sem2.06, sem2.07,
                      sem2.08, sem2.09, sem2.10, sem2.11, sem2.12, sem2.13, sem2.14),
  r2Plot = plotR2(r2data),
  # tables
  itemTable = makeItemTable(),
  # main results with exclusions
  dExc = d[d$egame.cmpSH.T10 == 1 & d$egame.cmpTG.T10 == 1 & d$egame.cmpPGG.T10 == 1 & d$egame.cmpDG.T10 == 1,],
  semExc1 = semModel1Exc(dExc),
  semExc2 = semModel2Exc(dExc),
  medExc1 = medModel1Exc(dExc),
  medExc2 = medModel2Exc(dExc),
  # main results with public goods game
  semPGG1 = semModel1PGG(dExc),
  semPGG2 = semModel2PGG(dExc),
  medPGG1 = medModel1PGG(dExc),
  medPGG2 = medModel2PGG(dExc),
  # manuscript
  manuscript = rmarkdown::render(knitr_in("manuscript.Rmd"), quiet = TRUE)
)
